import { AirVent, MapPin, Bluetooth, Users, Sunrise, Gauge, Wifi, Briefcase } from "lucide-react"

// Feature icon mapping
export const featureIcons: Record<string, any> = {
  AC: AirVent,
  GPS: MapPin,
  Bluetooth: Bluetooth,
  "Child Seat": Users,
  Sunroof: Sunrise,
  Autopilot: Gauge,
  WiFi: Wifi,
  "Heated Seats": Sunrise,
  "Parking Sensors": Gauge,
  "Leather Seats": Briefcase,
}

// Sample car data
export const carsData = [
  {
    id: 1,
    name: "Tesla Model 3",
    type: "Electric",
    image: "https://images.unsplash.com/photo-1560958089-b8a1929cea89?q=80&w=2071&auto=format&fit=crop",
    price: 89,
    discountedPrice: 75,
    passengers: 5,
    luggage: 2,
    transmission: "Automatic",
    features: ["AC", "GPS", "Bluetooth", "Autopilot"],
    rating: 4.9,
    reviewCount: 124,
    brand: "Tesla",
    isPopular: true,
    isNew: true,
    year: 2023,
  },
  {
    id: 2,
    name: "BMW X5",
    type: "SUV",
    image: "https://images.unsplash.com/photo-1556189250-72ba954cfc2b?q=80&w=2070&auto=format&fit=crop",
    price: 129,
    passengers: 7,
    luggage: 3,
    transmission: "Automatic",
    features: ["AC", "GPS", "Bluetooth", "Sunroof", "Child Seat"],
    rating: 4.7,
    reviewCount: 98,
    brand: "BMW",
    isPopular: true,
    isNew: false,
    year: 2022,
  },
  {
    id: 3,
    name: "Mercedes C-Class",
    type: "Sedan",
    image: "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?q=80&w=2070&auto=format&fit=crop",
    price: 99,
    passengers: 5,
    luggage: 2,
    transmission: "Automatic",
    features: ["AC", "GPS", "Bluetooth", "Sunroof"],
    rating: 4.5,
    reviewCount: 87,
    brand: "Mercedes",
    isPopular: false,
    isNew: false,
    year: 2022,
  },
  {
    id: 4,
    name: "Toyota Camry",
    type: "Sedan",
    image: "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?q=80&w=2069&auto=format&fit=crop",
    price: 65,
    passengers: 5,
    luggage: 2,
    transmission: "Automatic",
    features: ["AC", "Bluetooth"],
    rating: 4.3,
    reviewCount: 112,
    brand: "Toyota",
    isPopular: true,
    isNew: false,
    year: 2021,
  },
  {
    id: 5,
    name: "Porsche 911",
    type: "Sports",
    image: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?q=80&w=2070&auto=format&fit=crop",
    price: 199,
    passengers: 2,
    luggage: 1,
    transmission: "Automatic",
    features: ["AC", "GPS", "Bluetooth", "Sunroof"],
    rating: 4.9,
    reviewCount: 76,
    brand: "Porsche",
    isPopular: true,
    isNew: false,
    year: 2023,
  },
  {
    id: 6,
    name: "Honda CR-V",
    type: "SUV",
    image: "https://images.unsplash.com/photo-1568844293986-ca9e7bd13a3c?q=80&w=2070&auto=format&fit=crop",
    price: 79,
    passengers: 5,
    luggage: 3,
    transmission: "Automatic",
    features: ["AC", "GPS", "Bluetooth", "Child Seat"],
    rating: 4.4,
    reviewCount: 92,
    brand: "Honda",
    isPopular: false,
    isNew: true,
    year: 2022,
  },
  {
    id: 7,
    name: "Audi A4",
    type: "Sedan",
    image: "https://images.unsplash.com/photo-1606664608504-48fddb9e190b?q=80&w=2070&auto=format&fit=crop",
    price: 89,
    passengers: 5,
    luggage: 2,
    transmission: "Automatic",
    features: ["AC", "GPS", "Bluetooth", "Sunroof"],
    rating: 4.6,
    reviewCount: 84,
    brand: "Audi",
    isPopular: false,
    isNew: false,
    year: 2022,
  },
  {
    id: 8,
    name: "Toyota Sienna",
    type: "Van",
    image: "https://images.unsplash.com/photo-1609520778163-d16a28af3495?q=80&w=1934&auto=format&fit=crop",
    price: 109,
    passengers: 8,
    luggage: 4,
    transmission: "Automatic",
    features: ["AC", "GPS", "Bluetooth", "Child Seat"],
    rating: 4.5,
    reviewCount: 67,
    brand: "Toyota",
    isPopular: false,
    isNew: false,
    year: 2021,
  },
  {
    id: 9,
    name: "Ford Mustang",
    type: "Sports",
    image: "https://images.unsplash.com/photo-1584345604476-8ec5e12e42dd?q=80&w=2070&auto=format&fit=crop",
    price: 129,
    passengers: 4,
    luggage: 1,
    transmission: "Manual",
    features: ["AC", "Bluetooth", "Sunroof"],
    rating: 4.8,
    reviewCount: 103,
    brand: "Ford",
    isPopular: true,
    isNew: false,
    year: 2023,
  },
]
